# Generated by Django 3.0.3 on 2020-02-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hubapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('technology', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=100)),
                ('link1', models.CharField(max_length=500)),
            ],
        ),
    ]
